# Generated by Django 3.0.6 on 2020-06-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_option',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_options',
            field=models.ManyToManyField(to='app.MenuOption'),
        ),
    ]
