# Generated by Django 3.0.6 on 2020-06-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slack_user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
