# Generated by Django 3.0.6 on 2020-06-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200611_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Menu'),
            preserve_default=False,
        ),
    ]
