# Generated by Django 3.0.6 on 2020-06-16 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
